packages:
    - apps/email-templates-preview
    - apps/email-templates-preview/.react-email
    - apps/cronjobs
    - apps/scraper
    - apps/expo
    - apps/nextjs
    - apps/ui-docs-nextjs
    - apps/ui-docs-expo
    - packages/api
    - packages/auth
    - packages/db
    - packages/ui
    - packages/email-templates
    - packages/message-broker
    - packages/modules/*
    - packages/config/*
